using System.Text;
using NBT;
using Tests;

var cases = BlobTestCases.All;

string outputPath = args.Length > 0
    ? Path.GetFullPath(args[0])
    : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../Tests/GeneratedBlobs.cs"));

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("// This file is generated by the BlobGenerator project.");
sb.AppendLine("// To regenerate, run: dotnet run --project BlobGenerator");
sb.AppendLine("// DO NOT edit by hand — your changes will be overwritten.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("namespace Tests;");
sb.AppendLine();
sb.AppendLine("/// <summary>Expected binary blobs for <see cref=\"BinaryBlobTest\"/>.</summary>");
sb.AppendLine("internal static class GeneratedBlobs {");
sb.AppendLine("    public static readonly Dictionary<string, byte[]> All = new() {");

foreach ((string name, INbtTag tag) in cases) {
    byte[] blob = tag.Serialise();
    string hex = string.Join(", ", blob.Select(b => $"0x{b:X2}"));
    sb.AppendLine($"        [\"{name}\"] = [{hex}],");
}

sb.AppendLine("    };");
sb.AppendLine("}");

File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"Wrote {cases.Length} blobs to {outputPath}");
